# Generated by Django 5.2.6 on 2025-09-08 17:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id_number', models.CharField(unique=True)),
                ('grade', models.DateTimeField()),
                ('major', models.CharField(max_length=30)),
                ('GPA', models.DecimalField(decimal_places=2, max_digits=4)),
                ('enrollment_date', models.DateTimeField()),
                ('is_active', models.BooleanField()),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
