# Generated by Django 5.2.6 on 2025-09-08 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='age',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='adress',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='date_of_birth',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'female'), ('Other', 'Other')], null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Employee', 'Employee'), ('Teacher', 'Teacher'), ('Student', 'Student'), ('Parents', 'Parents'), ('Others', 'Others')], default='Student', max_length=50),
        ),
    ]
