# Generated by Django 5.2.6 on 2025-09-09 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_usermodel_age_usermodel_adress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='national_id_number',
            field=models.CharField(blank=True, null=True, unique=True),
        ),
    ]
